from models import Job

jobs: list[Job] = [
    Job(
        id="JOB-001",
        title="Senior AI Engineer",
        roleCategory="AI / ML",
        location="Bengaluru / Remote",
        experienceRange="5-8 years",
        description="Design and deploy scalable AI/ML systems serving millions of users.",
        status="Active",
        candidatesScanned=100000,
        topScore=92,
    ),
    Job(
        id="JOB-002",
        title="ML Platform Engineer",
        roleCategory="MLOps",
        location="Pune",
        experienceRange="4-7 years",
        description="Build and maintain ML infrastructure for training, serving, and monitoring.",
        status="Active",
        candidatesScanned=48200,
        topScore=89,
    ),
    Job(
        id="JOB-003",
        title="Cloud Solutions Architect",
        roleCategory="Cloud/DevOps",
        location="Hyderabad",
        experienceRange="7-10 years",
        description="Design cloud-native architectures on AWS/Azure with microservices.",
        status="Active",
        candidatesScanned=31500,
        topScore=87,
    ),
    Job(
        id="JOB-004",
        title="Backend Engineer - Data Pipeline",
        roleCategory="Backend",
        location="Mumbai",
        experienceRange="3-5 years",
        description="Build real-time and batch data pipelines processing terabytes daily.",
        status="Active",
        candidatesScanned=22100,
        topScore=94,
    ),
    Job(
        id="JOB-005",
        title="Frontend Lead - React",
        roleCategory="Frontend",
        location="Delhi / Remote",
        experienceRange="4-6 years",
        description="Lead frontend architecture for a next-gen analytics dashboard.",
        status="Active",
        candidatesScanned=18700,
        topScore=85,
    ),
    Job(
        id="JOB-006",
        title="Data Analyst - Growth",
        roleCategory="Data",
        location="Bengaluru",
        experienceRange="2-4 years",
        description="Drive growth decisions through data analysis and actionable insights.",
        status="Active",
        candidatesScanned=12400,
        topScore=78,
    ),
]
