# Each candidate is a dict with profile data + 14 ML feature columns.
# The ML features are synthetic for demo — replace with real data in production.

raw_candidates = [
    {
        # Profile
        "id": "CAND-001",
        "name": "Aarav Mehta",
        "role": "Senior ML Engineer",
        "company": "InnovaTech Solutions",
        "location": "Bengaluru, India",
        "experience": "7.2 years",
        "skills": ["Python", "Embeddings", "Retrieval", "Ranking", "MLOps"],
        "reason": "Strong production ML experience, high skill overlap, and strong career progression.",
        "hiddenGem": False,
        # 14 ML features
        "skills_overlap": 0.92,
        "years_experience": 7.2,
        "company_prestige": 4,
        "job_hop_freq": 2.8,
        "github_activity": 0.85,
        "open_source_contribs": 42,
        "leetcode_score": 0.88,
        "education_tier": 3,
        "certifications_count": 4,
        "project_complexity": 0.85,
        "tech_stack_diversity": 0.78,
        "endorsements_count": 156,
        "career_growth_rate": 1.2,
        "response_time_score": 0.82,
    },
    {
        "id": "CAND-002",
        "name": "Neha Iyer",
        "role": "AI Engineer",
        "company": "DataKraft",
        "location": "Pune, India",
        "experience": "5.4 years",
        "skills": ["Python", "LLM", "Vector Search", "FastAPI"],
        "reason": "Good AI engineering background with strong deployment and API experience.",
        "hiddenGem": False,
        "skills_overlap": 0.85,
        "years_experience": 5.4,
        "company_prestige": 3,
        "job_hop_freq": 2.2,
        "github_activity": 0.78,
        "open_source_contribs": 28,
        "leetcode_score": 0.82,
        "education_tier": 3,
        "certifications_count": 3,
        "project_complexity": 0.78,
        "tech_stack_diversity": 0.72,
        "endorsements_count": 98,
        "career_growth_rate": 0.95,
        "response_time_score": 0.88,
    },
    {
        "id": "CAND-003",
        "name": "Rohan Verma",
        "role": "Search Engineer",
        "company": "ZepScale",
        "location": "Hyderabad, India",
        "experience": "6.1 years",
        "skills": ["Search", "Ranking", "Elasticsearch", "Python"],
        "reason": "Strong search and ranking experience with high recruiter engagement.",
        "hiddenGem": False,
        "skills_overlap": 0.80,
        "years_experience": 6.1,
        "company_prestige": 3,
        "job_hop_freq": 3.0,
        "github_activity": 0.72,
        "open_source_contribs": 18,
        "leetcode_score": 0.75,
        "education_tier": 2,
        "certifications_count": 2,
        "project_complexity": 0.72,
        "tech_stack_diversity": 0.65,
        "endorsements_count": 84,
        "career_growth_rate": 0.8,
        "response_time_score": 0.90,
    },
    {
        "id": "CAND-004",
        "name": "Kavya Nair",
        "role": "Backend Engineer",
        "company": "CloudScale",
        "location": "Remote",
        "experience": "4.8 years",
        "skills": ["Docker", "AWS", "Terraform", "FastAPI"],
        "reason": "Hidden gem with strong backend-to-MLOps transition potential.",
        "hiddenGem": True,
        "skills_overlap": 0.65,
        "years_experience": 4.8,
        "company_prestige": 2,
        "job_hop_freq": 2.0,
        "github_activity": 0.92,
        "open_source_contribs": 56,
        "leetcode_score": 0.70,
        "education_tier": 2,
        "certifications_count": 5,
        "project_complexity": 0.68,
        "tech_stack_diversity": 0.82,
        "endorsements_count": 45,
        "career_growth_rate": 1.5,
        "response_time_score": 0.75,
    },
]
